/**
 * Instagram profile URLs for preloading
 * Extracted from data.txt
 */
export const PRELOAD_INSTAGRAM_URLS: string[] = [
  'https://www.instagram.com/tomvorwald/',
  'https://www.instagram.com/marcusschulz.official/',
  'https://www.instagram.com/hendrik.mati/',
  'https://www.instagram.com/johanneszimmerofficial/',
  'https://www.instagram.com/stefangraf_/',
  'https://www.instagram.com/saleshaxconsulting/',
  'https://www.instagram.com/elishacrowd/',
  'https://www.instagram.com/sabrinagraf_/',
  'https://www.instagram.com/tobiasknebel/',
  'https://www.instagram.com/thwimme/',
  'https://www.instagram.com/tradingcoacholi/',
  'https://www.instagram.com/mariolueddemann/',
  'https://www.instagram.com/matthias_beerbaum/',
  'https://www.instagram.com/jens_rabe/',
  // Note: Line 15 is a reel URL, skipping
  'https://www.instagram.com/kaan.dxb/',
  'https://www.instagram.com/karl_ess/',
  'https://www.instagram.com/juergen_hoeller/',
  'https://www.instagram.com/tobias_beck_official/',
  'https://www.instagram.com/oscar.karem/',
  'https://www.instagram.com/biyon/',
  'https://www.instagram.com/alex_duesseldorf_fischer/',
  'https://www.instagram.com/rene.daytrading/',
  'https://www.instagram.com/michael_mross/',
  'https://www.instagram.com/pavlodd/',
  'https://www.instagram.com/manuwagner.eth/',
  'https://www.instagram.com/swetlana_cielo/',
  'https://www.instagram.com/mischajaniec/',
  'https://www.instagram.com/lenny_schoenbach/',
  'https://www.instagram.com/patrick.reiser/',
  'https://www.instagram.com/lovelifepassport/',
  'https://www.instagram.com/roadtogloryjil/',
  'https://www.instagram.com/feliciasimon._/',
  'https://www.instagram.com/alexanderhartmann.de/',
  'https://www.instagram.com/investmentpunk/',
  'https://www.instagram.com/torbenplatzer/',
  'https://www.instagram.com/roadtogloryartie/',
  'https://www.instagram.com/dirkkreuter/',
  'https://www.instagram.com/kemalueres/',
  'https://www.instagram.com/coachburak/',
  'https://www.instagram.com/nikibrah/',
  'https://www.instagram.com/ben_ungeskriptet/',
  'https://www.instagram.com/christoph.today/',
  'https://www.instagram.com/kai_watchvice/',
  'https://www.instagram.com/ruben_schaefer/',
  'https://www.instagram.com/albertonodale/',
  'https://www.instagram.com/felixschmdt/',
  'https://www.instagram.com/ganzschoentutka/',
  'https://www.instagram.com/max_tornow/',
  'https://www.instagram.com/erschaffedichneu/',
  'https://www.instagram.com/david.doebele/',
  'https://www.instagram.com/marcel.schlee/',
  'https://www.instagram.com/greator/',
  'https://www.instagram.com/chris_schuppner/',
  'https://www.instagram.com/andreasjklar/',
  'https://www.instagram.com/bodoschaefer/',
  'https://www.instagram.com/torbenbaumdick/',
  'https://www.instagram.com/jonaseisert/',
  'https://www.instagram.com/businesswoman.de/',
  'https://www.instagram.com/liane_kautz/',
  'https://www.instagram.com/alexander_thieme/',
  'https://www.instagram.com/_robertblankenburg_/',
  'https://www.instagram.com/denys.schwarnweber/',
  'https://www.instagram.com/bejaminkurtz_de/',
  'https://www.instagram.com/frankasmusberlin/',
  'https://www.instagram.com/aleahbelluga_bazi/',
  'https://www.instagram.com/dr_martinrummeny/',
  'https://www.instagram.com/danielmatuschzik/',
  'https://www.instagram.com/matthiasaumann/',
  'https://www.instagram.com/hannahandthetriplets/',
  'https://www.instagram.com/felix_klemme/',
  'https://www.instagram.com/collin.brockmann/',
  'https://www.instagram.com/thaddaeuskoroma/',
  'https://www.instagram.com/peterbeercoaching/',
  'https://www.instagram.com/ruedigerdahlke/',
  'https://www.instagram.com/derstilberater/',
  'https://www.instagram.com/danielaminati/',
  'https://www.instagram.com/yvonneschoenau/',
  'https://www.instagram.com/lovetolisten.de/',
  'https://www.instagram.com/stefanverra/',
  'https://www.instagram.com/judithwilliams_official/',
  'https://www.instagram.com/leo.moves/',
  'https://www.instagram.com/viktoria.lauterbach/',
  'https://www.instagram.com/herr_tech/',
  'https://www.instagram.com/saschamuehle/',
  'https://www.instagram.com/martin_limbeck/',
  'https://www.instagram.com/stefan_fraedrich/',
  'https://www.instagram.com/olivergeisselhart_motivation/',
  'https://www.instagram.com/mr.yasin/',
  'https://www.instagram.com/the_bodycoach/',
  'https://www.instagram.com/immo.tommy/',
  'https://www.instagram.com/fullstack.de/',
  'https://www.instagram.com/gutachter.hauck/',
  'https://www.instagram.com/paartherapeutenpaar/',
  'https://www.instagram.com/ruthmarquardt/',
  'https://www.instagram.com/anna.holfeld/',
  'https://www.instagram.com/manuel.haas/',
  'https://www.instagram.com/relifeacademy/',
  'https://www.instagram.com/julesbikini/',
  'https://www.instagram.com/raphaelzenaty/',
  'https://www.instagram.com/leonie.kommoss/',
  'https://www.instagram.com/hussein.fht/',
  'https://www.instagram.com/sven.lamberty/',
  'https://www.instagram.com/datingbyklein/',
  'https://www.instagram.com/datingcoach_julia/',
  'https://www.instagram.com/lisa.mamacoach/',
  'https://www.instagram.com/danykahl.fitness/',
  'https://www.instagram.com/beziehungvorerziehung/',
  'https://www.instagram.com/weisheitenkraft/',
  'https://www.instagram.com/dariuskamadeva/',
  'https://www.instagram.com/alexanderrogowski_/',
  'https://www.instagram.com/physiogenetik/',
  'https://www.instagram.com/crohnisch/',
  'https://www.instagram.com/beziehungs.schluessel/',
  'https://www.instagram.com/alexstrrm/',
  'https://www.instagram.com/steffii_nmnn/',
  'https://www.instagram.com/lisa_maa/',
  'https://www.instagram.com/coachsophia_/',
  'https://www.instagram.com/dr_sascha_gail/',
  'https://www.instagram.com/vatercoach_pb/',
  'https://www.instagram.com/coachphilippberger/',
  'https://www.instagram.com/andrinafit/',
  'https://www.instagram.com/carla.rise/',
  'https://www.instagram.com/philip.hasselbach/',
  'https://www.instagram.com/alberto/',
  'https://www.instagram.com/franzifit/',
  'https://www.instagram.com/nataliavogel_/',
  'https://www.instagram.com/simon.mathis_/',
  'https://www.instagram.com/jan_bahmann/',
  'https://www.instagram.com/domtoelen/',
  'https://www.instagram.com/davidfranke93/',
  'https://www.instagram.com/andrea_ammann_mentoring/',
  'https://www.instagram.com/patrick_khatrao/',
  'https://www.instagram.com/florian_sondershausen/',
  'https://www.instagram.com/randolph.moreno.sommer/',
  'https://www.instagram.com/phil.poosch/',
  'https://www.instagram.com/dominique_dreher_official/',
  'https://www.instagram.com/kevin_glotzbach/',
  'https://www.instagram.com/damianlifecoach/',
  'https://www.instagram.com/mehr_geschaeft/',
  'https://www.instagram.com/therealassad/',
  'https://www.instagram.com/erdemduel/',
  'https://www.instagram.com/lennart_holdschick/',
  'https://www.instagram.com/giuseppe.pstn/',
  'https://www.instagram.com/ylli_sahiti/',
  'https://www.instagram.com/christiangebert_steuerberater/',
  // Note: Line 147 has malformed URL (missing 'h'), skipping
  'https://www.instagram.com/airbnb.marvin?igsh=MW9za2twZ3B4MjhodQ==',
  'https://www.instagram.com/saadiatouzri/',
  'https://www.instagram.com/johanneslebt/',
  'https://www.instagram.com/bastianbarami/',
];

/**
 * Extract username from Instagram URL
 * @param url - Instagram profile URL
 * @returns Username or null if invalid
 */
export function extractUsername(url: string): string | null {
  const match = url.match(/instagram\.com\/([^/?]+)/);
  return match ? match[1] : null;
}

/**
 * Get all usernames from the preload URLs
 */
export function getPreloadUsernames(): string[] {
  return PRELOAD_INSTAGRAM_URLS.map(extractUsername).filter(
    (username): username is string => username !== null
  );
}
