// import { CoachProfile } from './types';

// export const mockCoaches: CoachProfile[] = [
//   {
//     id: '1',
//     username: 'fitlifecoach',
//     profilePicture: '',
//     followersCount: 156000,
//     niche: 'Fitness',
//     verified: true,
//   },
//   {
//     id: '2',
//     username: 'bizgrowth_mentor',
//     profilePicture: '',
//     followersCount: 89000,
//     niche: 'Business',
//     verified: true,
//   },
//   {
//     id: '3',
//     username: 'wellness_journey',
//     profilePicture: 'wellness-1.jpg',
//     followersCount: 234000,
//     niche: 'Health & Wellness',
//     verified: true,
//   },
//   {
//     id: '4',
//     username: 'lifestyle_by_sarah',
//     profilePicture: 'lifestyle-1.jpg',
//     followersCount: 342000,
//     niche: 'Lifestyle',
//     verified: true,
//   },
//   {
//     id: '5',
//     username: 'marketingpro_alex',
//     profilePicture: 'business-2.jpg',
//     followersCount: 67000,
//     niche: 'Marketing',
//     verified: false,
//   },
//   {
//     id: '6',
//     username: 'finance_fundamentals',
//     profilePicture: 'business-3.jpg',
//     followersCount: 128000,
//     niche: 'Finance',
//     verified: true,
//   },
//   {
//     id: '7',
//     username: 'mindful_living_coach',
//     profilePicture: 'wellness-2.jpg',
//     followersCount: 45000,
//     niche: 'Mindfulness',
//     verified: false,
//   },
//   {
//     id: '8',
//     username: 'entrepreneur_hub',
//     profilePicture: 'business-4.jpg',
//     followersCount: 198000,
//     niche: 'Entrepreneurship',
//     verified: true,
//   },
//   {
//     id: '9',
//     username: 'nutrition_expert_jen',
//     profilePicture: 'wellness-3.jpg',
//     followersCount: 112000,
//     niche: 'Nutrition',
//     verified: true,
//   },
//   {
//     id: '10',
//     username: 'personal_growth_path',
//     profilePicture: 'lifestyle-2.jpg',
//     followersCount: 76000,
//     niche: 'Personal Development',
//     verified: false,
//   },
//   {
//     id: '11',
//     username: 'strongbody_strong mind',
//     profilePicture: 'fitness-2.jpg',
//     followersCount: 289000,
//     niche: 'Fitness',
//     verified: true,
//   },
//   {
//     id: '12',
//     username: 'startup_coach_mike',
//     profilePicture: 'business-5.jpg',
//     followersCount: 54000,
//     niche: 'Business',
//     verified: false,
//   },
//   {
//     id: '13',
//     username: 'holistic_health_hub',
//     profilePicture: 'wellness-4.jpg',
//     followersCount: 167000,
//     niche: 'Health & Wellness',
//     verified: true,
//   },
//   {
//     id: '14',
//     username: 'social_media_guru',
//     profilePicture: 'business-6.jpg',
//     followersCount: 423000,
//     niche: 'Marketing',
//     verified: true,
//   },
//   {
//     id: '15',
//     username: 'invest_smart_daily',
//     profilePicture: 'business-7.jpg',
//     followersCount: 93000,
//     niche: 'Finance',
//     verified: false,
//   },
//   {
//     id: '16',
//     username: 'yoga_and_beyond',
//     profilePicture: 'wellness-5.jpg',
//     followersCount: 201000,
//     niche: 'Mindfulness',
//     verified: true,
//   },
//   {
//     id: '17',
//     username: 'scale_your_startup',
//     profilePicture: 'business-8.jpg',
//     followersCount: 138000,
//     niche: 'Entrepreneurship',
//     verified: true,
//   },
//   {
//     id: '18',
//     username: 'plant_based_coach',
//     profilePicture: 'wellness-6.jpg',
//     followersCount: 87000,
//     niche: 'Nutrition',
//     verified: false,
//   },
//   {
//     id: '19',
//     username: 'level_up_your_life',
//     profilePicture: 'lifestyle-3.jpg',
//     followersCount: 156000,
//     niche: 'Personal Development',
//     verified: true,
//   },
//   {
//     id: '20',
//     username: 'hiit_fitness_expert',
//     profilePicture: 'fitness-3.jpg',
//     followersCount: 312000,
//     niche: 'Fitness',
//     verified: true,
//   },
//   {
//     id: '21',
//     username: 'creative_entrepreneur',
//     profilePicture: 'business-9.jpg',
//     followersCount: 64000,
//     niche: 'Entrepreneurship',
//     verified: false,
//   },
//   {
//     id: '22',
//     username: 'zen_living_daily',
//     profilePicture: '/avatars/wellness-7.jpg',
//     followersCount: 119000,
//     niche: 'Mindfulness',
//     verified: true,
//   },
//   {
//     id: '23',
//     username: 'content_marketing_lab',
//     profilePicture: '/avatars/business-10.jpg',
//     followersCount: 178000,
//     niche: 'Marketing',
//     verified: true,
//   },
//   {
//     id: '24',
//     username: 'wealth_builder_coach',
//     profilePicture: '/avatars/business-11.jpg',
//     followersCount: 245000,
//     niche: 'Finance',
//     verified: true,
//   },
//   {
//     id: '25',
//     username: 'macro_nutrition_coach',
//     profilePicture: '/avatars/wellness-8.jpg',
//     followersCount: 98000,
//     niche: 'Nutrition',
//     verified: false,
//   },
// ];
